import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {G,AU,SOLAR_MASS,planets,initialSystem,body,step,stableStep} from './physics.js';
import './style.css';
import {LightFlight,lightTravelSeconds} from './light-flight.js';
import {resolveCollisions} from './collisions.js';
import {createBodyPreview} from './preview.js';
import {createImpactEffects} from './impact-effects.js';
const mount=document.querySelector('#universe'),panel=document.querySelector('#panel'),tip=document.querySelector('#tooltip');
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',alpha:false,logarithmicDepthBuffer:true});renderer.setClearColor('#050614');renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;mount.append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Mapa 3D. Przeciągnij, aby obrócić. Kółko: zoom. Prawy przycisk: przesuń. Kliknij ciało lub przestrzeń. Spacja: pauza. Escape: zamknij.');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.0000001,2000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=.00001;controls.maxDistance=260;controls.zoomToCursor=true;controls.enablePan=true;controls.panSpeed=.7;
const home=new THREE.Vector3(0,31,43).multiplyScalar(Math.max(1,1.15/(innerWidth/innerHeight)));camera.position.copy(home);controls.target.set(0,0,0);controls.update();scene.add(new THREE.AmbientLight('#bac8f3',.19));const sunlight=new THREE.PointLight('#fff1d8',3.6,0,0);scene.add(sunlight);
const preview=createBodyPreview(),impactEffects=createImpactEffects(scene);
let bs=initialSystem(),views=new Map(),selected=null,follow=null,paused=false,speed=2,elapsed=0,compressed=true,lastOrbit=0,spawnAt=new THREE.Vector3(),restoreFocus=null;
let lightFlight=null,flightPrevious=null,flightStops=[],flightTrueScale=false;
const flightLabels=document.createElement("div");flightLabels.id="flight-labels";document.body.append(flightLabels);
const flightHud=document.createElement('div');flightHud.id='light-flight';flightHud.hidden=true;document.body.append(flightHud);
const flightRail=document.createElement('nav');flightRail.id='flight-rail';flightRail.hidden=true;flightRail.setAttribute('aria-label','Postęp lotu przez planety');document.body.append(flightRail);
const timeDock=document.createElement('nav');timeDock.id='time-dock';timeDock.setAttribute('aria-label','Sterowanie czasem i lotem');
timeDock.innerHTML=`<button id="dock-pause" aria-label="Wstrzymaj symulację"><span id="dock-pause-icon">Ⅱ</span><span id="dock-pause-label">Pauza</span></button><div class="dock-divider"></div><label for="dock-speed">Tempo</label><select id="dock-speed" aria-label="Tempo symulacji"><option value="realtime" hidden>1 : 1</option>${[.02,.1,.5,2,10,50].map(s=>`<option value="${s}" ${s===2?'selected':''}>${s} dni / s</option>`).join('')}</select><div class="dock-divider"></div><button id="dock-flight"><span class="dock-c">c</span><span id="dock-flight-label">Lot światła</span></button>`;
document.body.append(timeDock);
document.querySelector('#dock-pause').onclick=()=>setPaused(!paused);
document.querySelector('#dock-speed').onchange=e=>{if(lightFlight)lightFlight.setRate(+e.target.value,performance.now());else speed=+e.target.value};
document.querySelector('#dock-flight').onclick=()=>lightFlight?stopLightFlight():startLightFlight();
let dockState='';
function syncTimeDock(){const state=`${paused}:${speed}:${lightFlight?.rate??0}`;if(state===dockState)return;dockState=state;const pauseButton=document.querySelector('#dock-pause');pauseButton.setAttribute('aria-label',paused?'Wznów symulację':'Wstrzymaj symulację');pauseButton.setAttribute('aria-pressed',String(paused));document.querySelector('#dock-pause-icon').textContent=paused?'▶':'Ⅱ';document.querySelector('#dock-pause-label').textContent=paused?'Wznów':'Pauza';const select=document.querySelector('#dock-speed');select.disabled=false;const mode=lightFlight?'flight':'normal';if(select.dataset.mode!==mode){select.dataset.mode=mode;select.innerHTML=(lightFlight?[1,10,60,300,1000]:[.02,.1,.5,2,10,50]).map(s=>`<option value="${s}">${s}${lightFlight?' ×':' dni / s'}</option>`).join('')}select.value=String(lightFlight?lightFlight.rate:speed);document.querySelector('#dock-flight-label').textContent=lightFlight?'Zakończ lot':'Lot światła';document.querySelector('#dock-flight').setAttribute('aria-pressed',String(!!lightFlight));timeDock.classList.toggle('in-flight',!!lightFlight);const panelPause=document.querySelector('#pause');if(panelPause)panelPause.textContent=paused?'▶':'Ⅱ';const panelSpeed=document.querySelector('#speed');if(panelSpeed){if(lightFlight)panelSpeed.options[0].textContent=`Lot · ${lightFlight.rate} ×`;else panelSpeed.value=String(speed);}}
const loader=new THREE.TextureLoader(),textures={};for(const key of ['sun','mercury','venus','earth','mars','jupiter','saturn','uranus','neptune','moon']){textures[key]=loader.load(`/textures/${key}.jpg`);textures[key].colorSpace=THREE.SRGBColorSpace;textures[key].anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy())}
const vector=(a)=>new THREE.Vector3(...a);
function mapped(p){const v=vector(p),r=v.length();return compressed?v.multiplyScalar(r?3.6*Math.pow(r,.57)/r:1):v.multiplyScalar(6)}
function displayed(b){if(lightFlight){const stop=flightStops.find(s=>s.id===b.id);if(stop)return mapped(lightFlight.origin).addScaledVector(vector(lightFlight.direction),stop.distance*6);if(b.parent){const host=bs.find(x=>x.id===b.parent);if(host)return displayed(host).add(flightTrueScale?vector(b.p).sub(vector(host.p)).multiplyScalar(6):vector(b.p).sub(vector(host.p)).normalize().multiplyScalar(radius(host)*2.5))}if(b.key==='sun')return mapped(lightFlight.origin);}if(!compressed)return mapped(b.p);if(b.parent){const host=bs.find(x=>x.id===b.parent);if(host){const d=vector(b.p).sub(vector(host.p)),r=d.length();return displayed(host).add(d.multiplyScalar(r?((radius(host)*1.8+Math.pow(r*AU/200000,.55)*.24)/r):1))}}return mapped(b.p)}
function radius(b){if(lightFlight){if(flightTrueScale)return b.radius/AU*6;if(b.key==='sun')return .12;if(b.parent)return .008;return .018+.095*Math.pow(b.radius/69911,.6)}if(!compressed)return b.radius/AU*6;if(b.key==='sun')return 1.02;if(b.key==='blackhole')return .5*Math.pow(b.mass,.15);if(b.parent)return b.irregular?.029:Math.max(.035,b.radius/22000);if(b.key==='comet')return .055;if(b.key==='fragment')return .035+.16*Math.pow(b.radius/69911,.5);return .10+.57*Math.pow(b.radius/69911,.62)}
const sphere=new THREE.SphereGeometry(1,56,40);
function glow(color,size){const mat=new THREE.ShaderMaterial({uniforms:{tint:{value:new THREE.Color(color)}},vertexShader:`
#include <common>
#include <logdepthbuf_pars_vertex>
varying vec2 vUv;
void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);
#include <logdepthbuf_vertex>
}`,fragmentShader:`
#include <common>
#include <logdepthbuf_pars_fragment>
varying vec2 vUv;uniform vec3 tint;
void main(){
#include <logdepthbuf_fragment>
float r=length(vUv-.5)*2.;float corona=exp(-max(0.,r-.19)*9.)*.8;float outer=exp(-r*4.)*.12;float rays=1.+.06*sin(atan(vUv.y-.5,vUv.x-.5)*24.);float a=(corona*rays+outer)*(1.-smoothstep(.75,1.,r));gl_FragColor=vec4(tint,a);
}`,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false});const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),mat);return m}

function addView(b){const group=new THREE.Group();scene.add(group);let geo=sphere;if(b.irregular||b.key==='comet'){geo=new THREE.IcosahedronGeometry(1,2);const a=geo.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),z=a.getZ(i),f=1+.12*Math.sin(x*18+y*13+z*8);a.setXYZ(i,x*f*1.3,y*f*.78,z*f)}geo.computeVertexNormals()}
 const mat=b.key==='sun'?new THREE.MeshBasicMaterial({map:textures.sun,color:new THREE.Color('#fff2d0').multiplyScalar(1.65),toneMapped:false}):new THREE.MeshStandardMaterial({map:textures[b.key]||textures.moon,color:b.key==='moon'?b.color:b.key==='blackhole'?'#000000':'#ffffff',roughness:1,metalness:0});if(b.key==='blackhole')mat.map=null;
 const axis=new THREE.Group();axis.rotation.z=THREE.MathUtils.degToRad(b.tilt);group.add(axis);const mesh=new THREE.Mesh(geo,mat);axis.add(mesh);mesh.userData.id=b.id;
 let halo=null;if(b.key==='sun'){halo=glow('#ffb863',9.5);group.add(halo)}
 if(b.key==='earth'){const atmo=new THREE.Mesh(sphere,new THREE.ShaderMaterial({vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n;varying vec3 v;void main(){float a=pow(1.-max(dot(n,v),0.),4.);gl_FragColor=vec4(.18,.46,.9,a*.38);}',transparent:true,depthWrite:false}));atmo.scale.setScalar(1.035);mesh.add(atmo)}
 if(['saturn','uranus','blackhole'].includes(b.key)){const ringGeo=new THREE.RingGeometry(b.key==='blackhole'?1.25:1.35,b.key==='uranus'?1.9:2.35,160,6);const arr=ringGeo.attributes.position,colors=[];for(let i=0;i<arr.count;i++){const r=Math.hypot(arr.getX(i),arr.getY(i)),f=.55+.28*Math.sin(r*100)+.13*Math.sin(r*270);const c=new THREE.Color(b.key==='blackhole'?'#ffaa53':b.color).multiplyScalar(f);colors.push(c.r,c.g,c.b)}ringGeo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const ring=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.DoubleSide,transparent:true,opacity:b.key==='uranus'?.25:.65}));ring.rotation.x=Math.PI/2;mesh.add(ring)}
 const orbitGeo=new THREE.BufferGeometry();orbitGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(257*3),3).setUsage(THREE.DynamicDrawUsage));const orbit=new THREE.Line(orbitGeo,new THREE.LineBasicMaterial({color:b.color,transparent:true,opacity:b.parent?.10:.19,depthWrite:false}));orbit.frustumCulled=false;scene.add(orbit);
 const trailGeo=new THREE.BufferGeometry();trailGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(512*3),3).setUsage(THREE.DynamicDrawUsage));trailGeo.setDrawRange(0,0);const trail=new THREE.Line(trailGeo,new THREE.LineBasicMaterial({color:b.color,transparent:true,opacity:.3}));trail.frustumCulled=false;scene.add(trail);views.set(b.id,{group,axis,mesh,halo,orbit,trail,history:[]});}
function disposeView(id){const v=views.get(id);if(!v)return;scene.remove(v.group,v.orbit,v.trail);v.group.traverse(o=>{if(o.isMesh){if(o.geometry!==sphere)o.geometry.dispose();o.material.dispose()}});v.orbit.geometry.dispose();v.orbit.material.dispose();v.trail.geometry.dispose();v.trail.material.dispose();views.delete(id);if(selected===id){selected=null;panel.hidden=true}if(follow===id)follow=null}
bs.forEach(addView);
// Dynamic point attributes are uploaded to WebGL for stars, asteroid belt and comet dust.
const count=4800,pointGeo=new THREE.BufferGeometry(),attrs={position:new Float32Array(count*3),size:new Float32Array(count),color:new Float32Array(count*3),brightness:new Float32Array(count),params:new Float32Array(count*2)};let seed=72831;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}const asteroidData=[];
for(let i=0;i<count;i++){let p;if(i<3000){const z=rand()*2-1,t=rand()*Math.PI*2,r=140+rand()*160;p=[r*Math.sqrt(1-z*z)*Math.cos(t),r*z,r*Math.sqrt(1-z*z)*Math.sin(t)];attrs.size[i]=rand()<.035?2.8:rand()*1.2+.45;attrs.brightness[i]=.15+rand()*.5}else if(i<4200){const r=2.15+rand()*1.05,t=rand()*Math.PI*2;asteroidData.push({i,r,t,y:(rand()-.5)*.16});p=mapped([r*Math.cos(t),(rand()-.5)*.12,r*Math.sin(t)]).toArray();attrs.size[i]=.55+rand()*.7;attrs.brightness[i]=.09+rand()*.15}else{p=[0,0,0];attrs.size[i]=0;attrs.brightness[i]=0}attrs.position.set(p,i*3);const c=new THREE.Color().setHSL(.58+rand()*.08,.1+rand()*.2,.65+rand()*.3);attrs.color.set([c.r,c.g,c.b],i*3);attrs.params.set([rand()*Math.PI*2,rand()],i*2)}
for(const [key,value] of Object.entries(attrs))pointGeo.setAttribute(key,new THREE.BufferAttribute(value,key==='position'||key==='color'?3:key==='params'?2:1).setUsage(THREE.DynamicDrawUsage));
const pointMaterial=new THREE.ShaderMaterial({uniforms:{time:{value:0},dpr:{value:renderer.getPixelRatio()}},vertexShader:'attribute float size;attribute float brightness;attribute vec3 color;attribute vec2 params;varying vec3 c;varying float a;uniform float time;uniform float dpr;void main(){c=color;a=brightness*(.9+.1*sin(time*.3+params.x));vec4 mv=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*mv;gl_PointSize=size*dpr;}',fragmentShader:'varying vec3 c;varying float a;void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;gl_FragColor=vec4(c,a*(1.-smoothstep(.1,1.,r)));}',transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});const points=new THREE.Points(pointGeo,pointMaterial);points.frustumCulled=false;scene.add(points);
const selection=new THREE.Mesh(new THREE.RingGeometry(1.25,1.263,100),new THREE.MeshBasicMaterial({color:'#c7d9ef',transparent:true,opacity:.65,side:THREE.DoubleSide,depthTest:false}));selection.visible=false;scene.add(selection);
function updateOrbits(){if(lightFlight){for(const v of views.values()){v.orbit.visible=false;v.trail.visible=false}return}for(const b of bs){const view=views.get(b.id),host=bs.find(x=>x.id===b.parent)||bs.find(x=>x.key==='sun');if(!host||host===b){view.orbit.visible=false;continue}const r=vector(b.p).sub(vector(host.p)),v=vector(b.v).sub(vector(host.v)),mu=G*(host.mass+b.mass),h=r.clone().cross(v),ev=v.clone().cross(h).divideScalar(mu).sub(r.clone().normalize()),e=ev.length(),p=h.lengthSq()/mu;if(!Number.isFinite(p)||p<1e-12){view.orbit.visible=false;continue}const x=e>.00001?ev.normalize():r.clone().normalize(),y=h.normalize().cross(x).normalize();const max=e<1?Math.PI:Math.acos(-1/e)*.96,arr=view.orbit.geometry.attributes.position;for(let i=0;i<257;i++){const t=-max+i/256*max*2,rr=Math.min(200,p/(1+e*Math.cos(t))),pos=x.clone().multiplyScalar(rr*Math.cos(t)).addScaledVector(y,rr*Math.sin(t)).add(vector(host.p));let out;if(b.parent&&compressed){out=displayed(host).add(pos.sub(vector(host.p)).normalize().multiplyScalar(radius(host)*1.8+Math.pow(rr*AU/200000,.55)*.24))}else out=mapped(pos.toArray());arr.setXYZ(i,out.x,out.y,out.z)}arr.needsUpdate=true;view.orbit.visible=true;}}
updateOrbits();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let down=null,lastTouchTimer;
function pointRay(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera)}
function hit(e){pointRay(e);const hits=ray.intersectObjects([...views.values()].map(v=>v.mesh),false);return hits[0]?.object.userData.id||null}
function location(e){pointRay(e);const pos=new THREE.Vector3();if(!ray.ray.intersectPlane(plane,pos))pos.copy(controls.target);const r=pos.length();return compressed?pos.multiplyScalar(r?Math.pow(r/3.6,1/.57)/r:1):pos.divideScalar(6)}
renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};if(e.pointerType==='touch')lastTouchTimer=setTimeout(()=>{spawnAt.copy(location(e));showSpawner()},650)});
renderer.domElement.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)clearTimeout(lastTouchTimer);if(e.buttons){tip.hidden=true;return}const id=hit(e);renderer.domElement.style.cursor=id?'pointer':'grab';tip.hidden=!id;if(id){tip.textContent=bs.find(b=>b.id===id)?.name;tip.style.left=Math.min(innerWidth-110,e.clientX+16)+'px';tip.style.top=(e.clientY+16)+'px'}});
renderer.domElement.addEventListener('pointerup',e=>{clearTimeout(lastTouchTimer);if(lightFlight||e.button!==0||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5){down=null;return}down=null;const id=hit(e);if(id){selected=id;showBody()}else{spawnAt.copy(location(e));showSpawner()}tip.hidden=true});
renderer.domElement.addEventListener('dblclick',e=>{const id=hit(e);if(id)focusBody(id)});
function shell(title,content){preview.clear();restoreFocus=document.activeElement;panel.innerHTML=`<div class="panel-head"><h2>${title}</h2><button class="close" aria-label="Zamknij">×</button></div>${content}`;panel.hidden=false;panel.querySelector('.close').onclick=closePanel}
function closePanel(){preview.clear();panel.hidden=true;selected=null;restoreFocus?.focus?.()}
const row=(label,html)=>`<div class="row"><label>${label}</label>${html}</div>`;
const num=(id,value,step='any')=>`<input id="${id}" type="number" step="${step}" value="${Number(value.toPrecision(7))}" aria-label="${id}">`;
const vecFields=(prefix,arr,label)=>`<label class="field-title">${label}</label><div class="vector">${arr.map((n,i)=>num(prefix+['X','Y','Z'][i],n)).join('')}</div>`;
function getVec(prefix){return ['X','Y','Z'].map(k=>Number(document.getElementById(prefix+k).value))}
function showBody(){if(lightFlight){const id=selected;stopLightFlight();selected=id}const b=bs.find(x=>x.id===selected);if(!b)return;const velocity=b.v.map(x=>x*AU/86400);shell(b.name,`${row('Masa · kg',num('mass',b.mass*SOLAR_MASS))}${row('Promień · km',num('radius',b.radius))}${row('Obrót · godz.',num('spin',b.spin))}${row('Nachylenie osi · °',num('tilt',b.tilt))}${vecFields('p',b.p,'Położenie X / Y / Z · AU')}${vecFields('v',velocity,'Prędkość X / Y / Z · km/s')}<div class="actions"><button class="action primary" id="apply">Zastosuj</button><button class="action" id="focus">Śledź</button></div><div class="separator"></div>${row('Zamień orbitę',`<select id="swap"><option value="">Wybierz ciało</option>${bs.filter(x=>x.a&&x.id!==b.id).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select>`)}<div class="actions"><button class="action" id="tools">Symulacja</button><button class="action danger" id="remove">Usuń</button></div><p class="muted" id="validation" role="status"></p>`);
 const previewHost=document.createElement('div');previewHost.className='body-preview';panel.querySelector('.panel-head').prepend(previewHost);preview.attach(previewHost,b,views.get(b.id));
 document.querySelector('#apply').onclick=()=>{const m=+document.querySelector('#mass').value,r=+document.querySelector('#radius').value,s=+document.querySelector('#spin').value,t=+document.querySelector('#tilt').value,p=getVec('p'),v=getVec('v');if(![m,r,s,t,...p,...v].every(Number.isFinite)||m<=0||m>1e35||r<=0||r>1e10||s===0||p.some(x=>Math.abs(x)>1e5)||v.some(x=>Math.abs(x)>299792)){document.querySelector('#validation').textContent='Sprawdź wartości: masa i promień muszą być dodatnie, obrót różny od zera.';return}b.mass=m/SOLAR_MASS;b.radius=r;b.spin=s;b.tilt=t;b.p=p;b.v=v.map(x=>x*86400/AU);clearTrails();updateOrbits();document.querySelector('#validation').textContent='Zapisano parametry.'};document.querySelector('#focus').onclick=()=>focusBody(b.id);document.querySelector('#tools').onclick=showTools;document.querySelector('#remove').onclick=()=>{bs=bs.filter(x=>x.id!==b.id);disposeView(b.id);closePanel();updateOrbits()};document.querySelector('#swap').onchange=e=>{const other=bs.find(x=>x.id===+e.target.value);if(!other)return;const oldP=[...b.p],oldV=[...b.v],otherP=[...other.p],otherV=[...other.v];for(const moon of bs.filter(x=>x.parent===b.id)){moon.p=moon.p.map((x,k)=>x+otherP[k]-oldP[k]);moon.v=moon.v.map((x,k)=>x+otherV[k]-oldV[k])}for(const moon of bs.filter(x=>x.parent===other.id)){moon.p=moon.p.map((x,k)=>x+oldP[k]-otherP[k]);moon.v=moon.v.map((x,k)=>x+oldV[k]-otherV[k])}b.p=otherP;b.v=otherV;other.p=oldP;other.v=oldV;clearTrails();updateOrbits();showBody()}}
function showSpawner(){if(lightFlight)stopLightFlight();selected=null;shell('Nowe ciało',`${row('Rodzaj',`<select id="kind"><option value="comet">Kometa</option><option value="blackhole">Czarna dziura</option>${planets.map(p=>`<option value="${p[1]}">${p[0]}</option>`).join('')}</select>`)}${vecFields('spawn',spawnAt.toArray(),'Położenie X / Y / Z · AU')}${row('Prędkość · km/s',num('launch',25))}${row('Kierunek · °',num('angle',120))}${row('Wznoszenie · °',num('pitch',0))}<div class="actions"><button class="action primary" id="create">Dodaj</button><button class="action" id="tools">Symulacja</button></div><p class="muted" id="validation" role="status"></p>`);document.querySelector('#tools').onclick=showTools;document.querySelector('#create').onclick=()=>{const key=document.querySelector('#kind').value,p=getVec('spawn'),sp=+document.querySelector('#launch').value,a=+document.querySelector('#angle').value*Math.PI/180,pitch=+document.querySelector('#pitch').value*Math.PI/180;if(![...p,sp,a,pitch].every(Number.isFinite)||Math.abs(sp)>299792||p.some(x=>Math.abs(x)>1e5)){document.querySelector('#validation').textContent='Podaj prawidłowe położenie i prędkość.';return}if(bs.length>=100){document.querySelector('#validation').textContent='Osiągnięto limit 100 ciał.';return}const def=planets.find(x=>x[1]===key),b=body({key,p,v:[Math.cos(a)*Math.cos(pitch)*sp*86400/AU,Math.sin(pitch)*sp*86400/AU,Math.sin(a)*Math.cos(pitch)*sp*86400/AU],name:def?def[0]:key==='comet'?'Kometa':'Czarna dziura',mass:def?def[5]:key==='blackhole'?5:1.1e-16,radius:def?def[6]:key==='blackhole'?14.77:4,spin:def?def[7]:12,tilt:def?def[8]:35,color:def?def[9]:key==='blackhole'?'#f9b572':'#a1d6df'});bs.push(b);addView(b);selected=b.id;updateOrbits();showBody()}}
function showTools(){selected=null;shell('Symulacja',`<div class="tools"><button id="pause" aria-label="Pauza">${paused?'▶':'Ⅱ'}</button><button id="zoom-in" aria-label="Przybliż">＋</button><button id="zoom-out" aria-label="Oddal">−</button><button id="home" aria-label="Domyślny widok">⌖</button></div>${row('Tempo',`<select id="speed">${lightFlight?`<option selected>Lot · ${lightFlight.rate} ×</option>`:''}${[.02,.1,.5,2,10,50].map(s=>`<option value="${s}" ${s===speed?'selected':''}>${s} dni / s</option>`).join('')}</select>`)}${row('Widok',`<select id="scale"><option value="visual" ${compressed?'selected':''}>Czytelny</option><option value="real" ${!compressed?'selected':''}>Rzeczywista skala</option></select>`)}${row('Wybierz ciało',`<select id="body"><option value="">—</option>${bs.map(b=>`<option value="${b.id}">${b.name}</option>`).join('')}</select>`)}<div class="actions"><button class="action" id="light-start">${lightFlight?'Zakończ lot światła':'Symulacja prędkości światła'}</button></div><div class="actions"><button class="action" id="add">Dodaj ciało</button><button class="action danger" id="restart">Od nowa</button></div>`);document.querySelector('#pause').onclick=e=>{setPaused(!paused);e.target.textContent=paused?'▶':'Ⅱ'};document.querySelector('#light-start').onclick=()=>lightFlight?stopLightFlight():startLightFlight();for(const id of ['speed','scale','zoom-in','zoom-out','home'])document.getElementById(id).disabled=!!lightFlight;document.querySelector('#zoom-in').onclick=()=>camera.position.lerp(controls.target,.25);document.querySelector('#zoom-out').onclick=()=>camera.position.sub(controls.target).multiplyScalar(1.3).add(controls.target);document.querySelector('#home').onclick=resetView;document.querySelector('#speed').onchange=e=>speed=+e.target.value;document.querySelector('#scale').onchange=e=>{compressed=e.target.value==='visual';clearTrails();updateOrbits()};document.querySelector('#body').onchange=e=>{selected=+e.target.value;if(selected)showBody()};document.querySelector('#add').onclick=()=>{spawnAt.set(2,0,0);showSpawner()};document.querySelector('#restart').onclick=restart}
function focusBody(id){if(lightFlight)stopLightFlight();follow=id;const b=bs.find(x=>x.id===id),target=displayed(b);controls.target.copy(target);camera.position.copy(target).add(new THREE.Vector3(0,2,4).multiplyScalar(Math.max(radius(b)*3,compressed?.3:.00001)));panel.hidden=true}
function resetView(){camera.fov=43;camera.updateProjectionMatrix();if(lightFlight)stopLightFlight();follow=null;controls.enabled=true;controls.enableDamping=false;camera.position.copy(home);controls.target.set(0,0,0);controls.update();controls.enableDamping=true;closePanel()}
function clearTrails(){for(const v of views.values()){v.history=[];v.trail.geometry.setDrawRange(0,0)}}
function restart(){lightFlight=null;flightPrevious=null;flightStops=[];flightTrueScale=false;flightRail.hidden=true;flightLabels.replaceChildren();flightHud.hidden=true;controls.enabled=true;lag=0;last=performance.now();spawnAt.set(0,0,0);lastOrbit=0;selected=null;follow=null;down=null;clearTimeout(lastTouchTimer);tip.hidden=true;selection.visible=false;preview.clear();impactEffects.clear();[...views.keys()].forEach(disposeView);bs=initialSystem();bs.forEach(addView);elapsed=0;paused=false;speed=2;compressed=true;updateOrbits();resetView()}
document.querySelector('#logo').onclick=()=>panel.hidden?showTools():closePanel();document.querySelector('#reset').onclick=restart;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();setPaused(!paused);if(!panel.hidden)showTools()}if(e.key==='Escape'){if(lightFlight)stopLightFlight();closePanel()};if(e.key.toLowerCase()==='r')restart();if(e.key.toLowerCase()==='a'){spawnAt.set(2,0,0);showSpawner()}if(e.key.toLowerCase()==='s')showTools()});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

function setPaused(value){const now=performance.now();if(lightFlight){if(value)lightFlight.pause(now);else lightFlight.resume(now)}paused=value;last=now;}
function startLightFlight(){
 if(lightFlight)return;
 const sun=bs.find(b=>b.key==='sun');if(!sun){shell('Brak Słońca','<p class="muted">Użyj Reset, aby przywrócić Słońce i rozpocząć lot.</p>');return}
 flightPrevious={speed,compressed,paused,camera:camera.position.clone(),target:controls.target.clone()};
 const direction=new THREE.Vector3(1,0,0);
 flightStops=planets.flatMap(p=>{const b=bs.find(b=>b.key===p[1]);return b?[{id:b.id,name:b.name,distance:p[2]}]:[]});
 flightLabels.innerHTML=flightStops.map(s=>`<span class="flight-body-label" data-body="${s.id}">${s.name}</span>`).join('');
 lightFlight=new LightFlight(sun.p,direction.toArray(),performance.now());follow=null;paused=false;speed=1/86400;compressed=false;lag=0;last=performance.now();
 controls.enabled=false;controls.enableDamping=false;controls.update();controls.enableDamping=true;closePanel();clearTrails();updateOrbits();
 flightHud.innerHTML=`<div class="flight-summary"><span class="flight-symbol">c</span><div><div class="flight-title">Lot światła <span id="flight-rate">1 ×</span></div><div id="flight-distance"></div><div id="flight-time"></div></div></div><div class="flight-arrival"><span class="flight-eyebrow">NASTĘPNE CIAŁO</span><strong id="flight-next-name"></strong><div id="flight-next"></div></div><label class="flight-scale"><input id="flight-scale-toggle" type="checkbox"> Rzeczywiste rozmiary i odległości</label><div class="flight-note" id="flight-scale-note">Bliski przelot · rozmiary powiększone</div>`;flightHud.hidden=false;
 flightTrueScale=false;flightRail.innerHTML=`<div class="rail-title">TRASA LOTU</div><div class="rail-track"><div class="rail-fill"></div><div class="rail-head"></div>${flightStops.map((s,i)=>`<span class="rail-stop" data-stop="${s.id}" style="top:${(i+1)/flightStops.length*100}%"><i></i>${s.name}</span>`).join('')}</div>`;flightRail.hidden=false;
 document.querySelector('#flight-scale-toggle').onchange=e=>{flightTrueScale=e.target.checked;document.querySelector('#flight-scale-note').textContent=flightTrueScale?'Rzeczywista skala · planety w linii demonstracyjnej':'Bliski przelot · rozmiary powiększone';};
 updateLightFlight(performance.now());
}
function stopLightFlight(){if(!lightFlight)return;lightFlight=null;flightStops=[];flightTrueScale=false;flightRail.hidden=true;flightLabels.replaceChildren();flightHud.hidden=true;flightRail.hidden=true;camera.fov=43;camera.updateProjectionMatrix();controls.enabled=true;const previous=flightPrevious;flightPrevious=null;speed=previous.speed;compressed=previous.compressed;paused=previous.paused;lag=0;last=performance.now();controls.enableDamping=false;camera.position.copy(previous.camera);controls.target.copy(previous.target);controls.update();controls.enableDamping=true;clearTrails();updateOrbits();if(!panel.hidden)showTools()}
const durationLabel=seconds=>{const s=Math.max(0,Math.floor(seconds));return `${Math.floor(s/3600)?Math.floor(s/3600)+':':''}${String(Math.floor(s/60)%60).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
function updateLightFlight(now){
 const flight=lightFlight,t=flight.seconds(now),distance=flight.distance(now),target=mapped(flight.origin);
 const nearest=[...flightStops].sort((a,b)=>Math.abs(a.distance-distance)-Math.abs(b.distance-distance))[0];
 const base=mapped(flight.position(now)).add(new THREE.Vector3(0,0,flightTrueScale?-.002:-.35));camera.position.copy(base);
 let look=target.clone();camera.fov=flightTrueScale?43:75;
 if(nearest&&!flightTrueScale){const planet=bs.find(b=>b.id===nearest.id),r=radius(planet),pos=displayed(planet),windowAU=Math.max(.12,nearest.distance*.08),gap=distance-nearest.distance,weight=Math.exp(-Math.pow(gap/windowAU,4));
 const close=pos.clone().add(new THREE.Vector3(r*(4+2*Math.tanh(gap/windowAU)),0,-r*5));camera.position.lerp(close,weight);
 const sunDirection=target.clone().sub(camera.position).normalize(),planetDirection=pos.clone().sub(camera.position).normalize();const framed=sunDirection.clone().add(planetDirection).normalize();look=camera.position.clone().add(sunDirection.lerp(framed,weight).normalize());}
 camera.updateProjectionMatrix();camera.lookAt(look);controls.target.copy(target);camera.updateMatrixWorld();
 document.querySelector('#flight-distance').textContent=`${distance.toFixed(3)} AU · ${(distance*AU/1e6).toFixed(2)} mln km`;
 document.querySelector('#flight-time').textContent=`Czas podróży ${durationLabel(t)} · c = 299 792 km/s`;
 document.querySelector('#flight-rate').textContent=`${flight.rate} ×${paused?' · pauza':''}`;
 const next=flightStops.find(p=>p.distance>distance);
 document.querySelector('#flight-next-name').textContent=next?next.name:'Za Neptunem';
 const remaining=next?Math.max(0,lightTravelSeconds(next.distance)-t):0;
 document.querySelector('#flight-next').textContent=next?`${(next.distance-distance).toFixed(3)} AU · ${durationLabel(remaining/flight.rate)} oglądania${paused?' (pauza)':''} · ${durationLabel(remaining)} lotu`:'Wszystkie planety za Tobą';
 for(const s of flightStops){const chip=flightRail.querySelector(`[data-stop="${s.id}"]`);chip.classList.toggle('passed',distance>=s.distance);chip.classList.toggle('upcoming',next?.id===s.id);}
 let progress=0;for(let i=0;i<flightStops.length;i++){const lower=i?flightStops[i-1].distance:0,upper=flightStops[i].distance;if(distance>=upper)progress=(i+1)/flightStops.length;else{progress=(i+Math.max(0,(distance-lower)/(upper-lower)))/flightStops.length;break}}flightRail.style.setProperty('--progress',String(Math.min(1,progress)));flightRail.setAttribute('aria-label',`Postęp lotu ${Math.round(progress*100)} procent trasy etapowej`);
 const closest=[...flightStops].sort((a,b)=>Math.abs(a.distance-distance)-Math.abs(b.distance-distance)).slice(0,2);
 for(const s of flightStops){const label=flightLabels.querySelector(`[data-body="${s.id}"]`),body=bs.find(b=>b.id===s.id),pos=displayed(body).project(camera);const visible=closest.includes(s)&&pos.z>-1&&pos.z<1&&Math.abs(pos.x)<.9&&Math.abs(pos.y)<.75;label.hidden=!visible;if(visible){label.style.left=((pos.x+1)*innerWidth/2)+'px';label.style.top=((-pos.y+1)*innerHeight/2+22)+'px'}}
}

function updateCometDust(now){const comets=bs.filter(b=>b.key==='comet'),sun=bs.find(b=>b.key==='sun');for(let i=4200;i<count;i++){if(!comets.length){attrs.size[i]=0;continue}const comet=comets[(i-4200)%comets.length],p=displayed(comet),origin=sun?displayed(sun):new THREE.Vector3(),away=p.clone().sub(origin).normalize(),t=((i-4200)/600+now*.000025)%1,dist=sun?vector(comet.p).distanceTo(vector(sun.p)):10,strength=Math.min(1,3/Math.max(.1,dist)),length=(2+3*strength)*t,spread=t*.24;const particle=p.addScaledVector(away,length);particle.x+=Math.sin(i*13.7)*spread;particle.y+=Math.cos(i*17.3)*spread;particle.z+=Math.sin(i*23.1)*spread;attrs.position.set(particle.toArray(),i*3);attrs.size[i]=1.1+2*(1-t);attrs.brightness[i]=(1-t)*.45*strength;attrs.color.set([.45,.75,.86],i*3)}for(const k of ['position','size','brightness','color','params'])pointGeo.attributes[k].needsUpdate=true;}
let last=performance.now(),frame=0,lag=0;
function handleCollisions(){const oldSelected=selected,oldFollow=follow,wasPanelVisible=!panel.hidden;const events=resolveCollisions(bs);if(!events.length)return;preview.clear();for(const event of events){const size=compressed?Math.max(.12,...event.sourceIds.map(id=>views.get(id)?.mesh.scale.x||.12)):event.radius/AU*6;impactEffects.add(event,mapped(event.p),size);event.removed.forEach(disposeView);for(const id of event.added)addView(bs.find(b=>b.id===id));if(event.sourceIds.includes(oldSelected))selected=event.survivor;if(event.sourceIds.includes(oldFollow))follow=event.survivor;}clearTrails();updateOrbits();if(selected&&wasPanelVisible)showBody();}
function animate(now){requestAnimationFrame(animate);const beforeElapsed=elapsed;const realDelta=Math.max(0,(now-last)/1000),delta=Math.min(realDelta,.05);last=now;if(!lightFlight&&!paused&&!document.hidden){lag=lightFlight?lag+realDelta/86400:Math.min(lag+delta*speed,.5);let steps=0;handleCollisions();while(lag>0&&steps<180){const dt=Math.min(lag,stableStep(bs));step(bs,dt);lag-=dt;elapsed+=dt;steps++;handleCollisions()}}else lag=0;
 for(const b of bs){const v=views.get(b.id);v.group.position.copy(displayed(b));v.mesh.scale.setScalar(radius(b));v.axis.rotation.z=b.tilt*Math.PI/180;v.mesh.rotation.y=((elapsed+(lightFlight?lightFlight.seconds(now)/86400:0))*24/b.spin*Math.PI*2)%(Math.PI*2);if(v.halo){v.halo.quaternion.copy(camera.quaternion);v.halo.scale.setScalar(radius(b)/1.02)};if(frame%8===0&&!paused&&!lightFlight){v.history.push(v.group.position.clone());if(v.history.length>512)v.history.shift();const a=v.trail.geometry.attributes.position;v.history.forEach((p,i)=>a.setXYZ(i,p.x,p.y,p.z));a.needsUpdate=true;v.trail.geometry.setDrawRange(0,v.history.length);v.trail.visible=!b.parent;}}
 const sun=bs.find(b=>b.key==='sun');sunlight.visible=!!sun;if(sun)sunlight.position.copy(displayed(sun));if(follow){const b=bs.find(x=>x.id===follow);if(b){const p=displayed(b),offset=camera.position.clone().sub(controls.target);controls.target.copy(p);camera.position.copy(p).add(offset)}}
 selection.visible=!!selected;const chosen=bs.find(x=>x.id===selected);if(chosen){selection.position.copy(displayed(chosen));selection.scale.setScalar(radius(chosen));selection.quaternion.copy(camera.quaternion)}
 if(now-lastOrbit>800){updateOrbits();lastOrbit=now}if(frame%3===0){for(const a of asteroidData){const t=a.t+elapsed*Math.sqrt(G/a.r**3),p=mapped([a.r*Math.cos(t),a.y,a.r*Math.sin(t)]);attrs.position.set(p.toArray(),a.i*3)}pointGeo.attributes.position.needsUpdate=true}updateCometDust(now);pointMaterial.uniforms.time.value=now*.001;impactEffects.update(paused?0:delta,mapped,elapsed-beforeElapsed);if(!panel.hidden)preview.update(bs.find(b=>b.id===selected),delta);syncTimeDock();if(lightFlight)updateLightFlight(now);else controls.update();for(const v of views.values())if(v.halo)v.halo.quaternion.copy(camera.quaternion);renderer.render(scene,camera);frame++}
requestAnimationFrame(animate);
// Exposed only as an explicit automation surface; no network or persistence.
window.solare={getState:()=>({paused,speed,elapsed,compressed,lightFlight:lightFlight?{rate:lightFlight.rate,seconds:lightFlight.seconds(performance.now()),distanceAU:lightFlight.distance(performance.now())}:null,bodies:bs.map(b=>({id:b.id,name:b.name,mass:b.mass,p:[...b.p],v:[...b.v]}))}),reset:restart,pause:()=>setPaused(true),resume:()=>setPaused(false),startLightFlight,stopLightFlight};
const modelContext=document.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_simulation',description:'Read current bodies, positions in AU and velocities in AU/day.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.solare.getState()},{name:'set_simulation_paused',description:'Pause or resume the current gravitational simulation.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(typeof input?.paused!=='boolean')throw new Error('paused must be a boolean');setPaused(input.paused);if(!panel.hidden)showTools();return {paused}}}]){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
